import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F4F1EB" },
  content: { padding: 22, paddingBottom: 118 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  eyebrow: {
    color: "#77817A",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
    marginBottom: 6,
  },
  title: { color: "#17201E", fontSize: 28, fontWeight: "800" },
  subtitle: { color: "#737A73", fontSize: 14, lineHeight: 21 },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#D8C29A",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { color: "#453923", fontSize: 18, fontWeight: "800" },
  notice: {
    backgroundColor: "#E2EEE7",
    borderRadius: 16,
    padding: 13,
    flexDirection: "row",
    gap: 9,
    alignItems: "center",
    marginBottom: 18,
  },
  noticeText: { color: "#31594C", flex: 1, fontSize: 12, lineHeight: 17 },
  hero: {
    backgroundColor: "#163B35",
    borderRadius: 26,
    minHeight: 190,
    padding: 22,
    flexDirection: "row",
    marginBottom: 22,
  },
  heroLabel: {
    color: "#AFCDBB",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  heroTitle: { color: "#FFF", fontSize: 23, fontWeight: "800", marginTop: 10 },
  heroMeta: { color: "#B8D0C3", fontSize: 13, marginTop: 5, marginBottom: 17 },
  routeArt: {
    position: "absolute",
    right: -12,
    bottom: 14,
    width: 130,
    height: 130,
    borderRadius: 70,
    backgroundColor: "#28584D",
    justifyContent: "center",
    alignItems: "center",
  },
  darkButton: {
    backgroundColor: "#26302D",
    borderRadius: 22,
    paddingVertical: 11,
    paddingHorizontal: 15,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  darkButtonSmall: {
    backgroundColor: "#17201E",
    borderRadius: 18,
    paddingVertical: 11,
    paddingHorizontal: 14,
    alignItems: "center",
  },
  darkButtonText: { color: "#FFF", fontSize: 12, fontWeight: "800" },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    marginTop: 8,
  },
  sectionTitle: { color: "#17201E", fontSize: 18, fontWeight: "800" },
  seeAll: { color: "#77817A", fontSize: 12 },
  actionRow: { flexDirection: "row", gap: 12, marginBottom: 22 },
  actionCard: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 15,
    flex: 1,
    minHeight: 130,
  },
  actionIcon: {
    backgroundColor: "#E9F0EA",
    width: 37,
    height: 37,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 13,
  },
  actionTitle: { color: "#17201E", fontSize: 15, fontWeight: "800" },
  actionBody: { color: "#858B84", fontSize: 11, lineHeight: 16, marginTop: 5 },
  steps: { backgroundColor: "#FFF", borderRadius: 21, padding: 16, gap: 17 },
  step: { flexDirection: "row", gap: 15 },
  stepNumber: { color: "#B28D54", fontSize: 12, fontWeight: "900", width: 23 },
  stepTitle: { color: "#25302B", fontSize: 14, fontWeight: "800" },
  stepBody: { color: "#81877F", fontSize: 12, lineHeight: 18, marginTop: 3 },
  pageHeading: { marginBottom: 20 },
  pageTitle: {
    color: "#17201E",
    fontSize: 29,
    fontWeight: "800",
    marginBottom: 6,
  },
  matchCard: {
    backgroundColor: "#FFF",
    borderRadius: 23,
    padding: 17,
    marginBottom: 14,
  },
  matchTop: { flexDirection: "row", gap: 11, alignItems: "center" },
  driverAvatar: {
    backgroundColor: "#E7D1A7",
    width: 43,
    height: 43,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  driverAvatarText: { color: "#54452C", fontWeight: "800", fontSize: 18 },
  cardKicker: {
    color: "#7B867D",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1,
  },
  cardTitle: {
    color: "#1C2723",
    fontSize: 15,
    fontWeight: "800",
    marginTop: 3,
    lineHeight: 21,
  },
  timePill: {
    backgroundColor: "#E9F0EA",
    borderRadius: 13,
    padding: 8,
    alignItems: "center",
  },
  timeBig: { color: "#28584D", fontWeight: "900", fontSize: 16 },
  timeSmall: { color: "#5E766C", fontSize: 9 },
  routeLine: {
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    marginTop: 16,
    paddingTop: 13,
    borderTopWidth: 1,
    borderTopColor: "#EEF0EC",
  },
  routeText: { color: "#59625C", fontSize: 11, fontWeight: "700" },
  dot: { color: "#A3AAA2" },
  explanation: { color: "#6D776F", fontSize: 11, marginTop: 8 },
  pickup: {
    color: "#28584D",
    backgroundColor: "#E5F2EA",
    padding: 11,
    borderRadius: 12,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 12,
  },
  cardActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
    marginTop: 15,
    alignItems: "center",
  },
  outlineButton: {
    borderColor: "#CBD8CE",
    borderWidth: 1,
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 13,
  },
  outlineText: { color: "#28584D", fontSize: 11, fontWeight: "800" },
  textButton: { padding: 7 },
  textButtonLabel: { color: "#9B5D4E", fontSize: 11, fontWeight: "800" },
  formCard: { backgroundColor: "#FFF", borderRadius: 23, padding: 18 },
  fieldLabel: {
    color: "#26332D",
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 12,
  },
  input: {
    backgroundColor: "#F7F8F5",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E0E5DF",
    color: "#34413A",
    fontSize: 14,
    paddingHorizontal: 14,
    paddingVertical: 13,
    marginBottom: 17,
  },
  timePickerContainer: {
    height: 110,
    backgroundColor: "#F7F8F5",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E0E5DF",
    marginBottom: 17,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  postButton: {
    backgroundColor: "#163B35",
    borderRadius: 20,
    paddingVertical: 13,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    marginTop: 20,
  },
  postButtonDisabled: { backgroundColor: "#AEB8B0" },
  postButtonText: { color: "#FFF", fontSize: 13, fontWeight: "800" },
  choice: {
    backgroundColor: "#F7F8F5",
    borderRadius: 14,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 9,
  },
  choiceActive: { backgroundColor: "#E2EEE7", borderWidth: 1, borderColor: "#8EB6A2" },
  choiceText: { color: "#34413A", fontSize: 14, fontWeight: "700", flex: 1 },
  choiceTextActive: { color: "#28584D" },
  helper: { color: "#838A83", fontSize: 12, lineHeight: 18, marginTop: 14 },
  profileCard: {
    backgroundColor: "#163B35",
    borderRadius: 23,
    padding: 22,
    alignItems: "center",
    marginBottom: 16,
  },
  bigAvatar: {
    width: 68,
    height: 68,
    borderRadius: 24,
    backgroundColor: "#D8C29A",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  bigAvatarText: { color: "#453923", fontWeight: "900", fontSize: 28 },
  profileName: { color: "#FFF", fontSize: 21, fontWeight: "800" },
  verified: { color: "#B8D0C3", marginTop: 7, fontSize: 12 },
  profileStats: {
    borderTopColor: "#37645A",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 14,
    marginTop: 18,
    paddingTop: 15,
    width: "100%",
  },
  profileStat: { flex: 1 },
  profileStatLabelRow: { alignItems: "center", flexDirection: "row", gap: 5 },
  profileStatLabel: { color: "#B8D0C3", fontSize: 11, fontWeight: "700" },
  profileStatValue: { color: "#FFF", fontSize: 13, fontWeight: "800", marginTop: 5 },
  profileSectionCard: {
    backgroundColor: "#FFF",
    borderRadius: 23,
    marginBottom: 12,
    padding: 18,
  },
  profileSectionHeader: { alignItems: "center", flexDirection: "row", gap: 11 },
  profileSectionIcon: {
    alignItems: "center",
    backgroundColor: "#E2EEE7",
    borderRadius: 13,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  profileSectionCopy: { flex: 1 },
  profileSectionEyebrow: { color: "#69736C", fontSize: 10, fontWeight: "800", letterSpacing: 0.8 },
  profileSectionTitle: { color: "#26332D", fontSize: 15, fontWeight: "800", marginTop: 3 },
  profileSectionBody: { color: "#58625B", fontSize: 13, lineHeight: 19, marginTop: 15 },
  preferenceDivider: { backgroundColor: "#E8ECE7", height: 1, marginVertical: 16 },
  preferenceLabel: { color: "#26332D", fontSize: 12, fontWeight: "800", marginBottom: 9 },
  preferenceRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  preferenceChip: { backgroundColor: "#F1F5F1", borderRadius: 20, paddingHorizontal: 10, paddingVertical: 7 },
  preferenceChipText: { color: "#416052", fontSize: 11, fontWeight: "700" },
  profilePrivacyCard: {
    alignItems: "flex-start",
    backgroundColor: "#EAF1EC",
    borderRadius: 18,
    flexDirection: "row",
    gap: 11,
    marginBottom: 16,
    padding: 15,
  },
  profilePrivacyCopy: { flex: 1 },
  profilePrivacyTitle: { color: "#28584D", fontSize: 13, fontWeight: "800" },
  profilePrivacyBody: { color: "#52625A", fontSize: 12, lineHeight: 17, marginTop: 4 },
  logoutButton: {
    alignItems: "center",
    borderColor: "#E8C3BD",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginBottom: 100,
    marginTop: 16,
    minHeight: 52,
  },
  logoutText: { color: "#A34E42", fontSize: 13, fontWeight: "800" },
  empty: {
    backgroundColor: "#FFF",
    borderRadius: 22,
    padding: 30,
    alignItems: "center",
    gap: 8,
  },
  nav: {
    position: "absolute",
    bottom: 14,
    left: 18,
    right: 18,
    backgroundColor: "#17201E",
    borderRadius: 27,
    minHeight: 68,
    paddingHorizontal: 8,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  navItem: { alignItems: "center", justifyContent: "center", minWidth: 66 },
  navIcon: {
    width: 31,
    height: 31,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  navIconActive: { backgroundColor: "#EDE9DF" },
  navLabel: { color: "#AEB9B0", fontSize: 9, marginTop: 3 },
  navLabelActive: { color: "#FFF", fontWeight: "800" },
});
